//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maui_WebView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maui_WebView.MyResources", typeof(MyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;video_player_wrapper&quot; style=&apos;height: 100%;width: 100%;display: inline-block;position: relative;&apos;&gt;
        ///    &lt;div id=&quot;dummy&quot; style=&quot;margin-top: 56.25%;&quot;&gt;&lt;/div&gt;
        ///    &lt;div id=&quot;video_player&quot; style=&quot;position:absolute;top:0;left:0;left: 0;right: 0;bottom:0;border:solid thin black;&quot;&gt;&lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;script type=&apos;text/javascript&apos; src=&quot;https://cdnapi.kaltura.com/p/2578031/sp/257803100/embedIframeJs/uiconf_id/44782721/partner_id/2578031&quot;&gt;&lt;/script&gt;
        ///&lt;script type=&apos;text/javascript&apos;&gt;
        ///    var playerConfig = {&quot;targe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Html {
            get {
                return ResourceManager.GetString("Html", resourceCulture);
            }
        }
    }
}
